version: "3.2"
services:
  collectiveaccess:
    build: ./collectiveaccess
    container_name: collectiveaccess
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_DISPLAY_NAME=${APP_DISPLAY_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - TIMEZONE=${TIMEZONE}
    volumes:
      - ./collectiveaccess/media:/var/www/providence/media
      - ./collectiveaccess/import:/var/www/providence/import
    ports:
      - 666:80
    restart: always
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=archive.meredithmonk.org
      - VALIDATION=http
    volumes:
      - ./swag-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
volumes:
  swag-config:
